### ISSUE TITLE
Renovate configuration improvements

### ISSUE THREAD

**Issue by sergeyshevch** [aenix-io/etcd-operator#136]
Follow up for #130 

Let's change some settings in renovate config to provide a better user experience:

- Enable auto merge by default when approved and can be merged
- Run tests/e2e tests automatically for renovate PRs
- As I remember, renovate can create a single PR to update multiple dependencies. Maybe we need to evaluate this setting?

**Comment by sergeyshevch** [comment]
@hiddenmarten What do you think about?

**Comment by hiddenmarten** [comment]
> Enable auto merge by default when approved and can be merged
1. Automerge will require additional effort because of GitHub limitations, take a look [here](https://github.com/renovatebot/renovate/issues/6473#issuecomment-855543240), anyway, I agree that it will be helpful.
2. I think it's better to auto-merge only dependencies with `minor` and `patch` updates to prevent breaking changes from major updates.
3. Automerge should be scheduled once a week, e.g. on weekends, as it isn't overwhelming for developers and CI.

> Run tests/e2e tests automatically for renovate PRs

Sure, it would be nice

> As I remember, renovate can create a single PR to update multiple dependencies. Maybe we need to evaluate this setting?

Yep, we can do it

**Comment by hiddenmarten** [comment]
Some additional improvements after the first renovate run:
- bump Golang version in GHA together with Dockefile
- bump Kubernetes version in Makefile together with Kubernetes go libraries.
