### ISSUE TITLE
Implement ".spec.image"

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#48]
Internaly we agreed to extend spec like this:

```diff
 ---
 apiVersion: etcd.aenix.io/v1alpha1
 kind: EtcdCluster
 metadata:
   name: test
   namespace: ns1
 spec:
+  image: "quay.io/coreos/etcd:v3.5.12"
   replicas: 3
 status:
   conditions:
   - lastProbeTime: null
 	lastTransitionTime: "2024-03-06T18:39:45Z"
 	status: "True"
 	type: Ready
```

**Comment by AlexGluck** [comment]
Suggest before accept PR #63 move key `image` under podSpec.

**Comment by gecube** [comment]
Agree with @AlexGluck that two keys would be too much. From the other point of view - `podSpec` is redundant for us. And we can just use the subset of keys from there like affinity, tolerations etc., which are important and should be customisable by the end user. But it will lead to massive work for preparing our own version of spec. Or otherwise we can just use `podSpec` and fill the proper spec fields by admission controller. So effectively taking `spec.image` and putting it into proper place of `podSpec`.

**Comment by sergeyshevch** [comment]
For now we have 2 options about field placement:
- `spec.image`
- `spec.podSpec.image`

We will decide it with community vote in https://t.me/etcd_operator/4054 and comment decision here
